//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaUygulamasi.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://repo.bahadirtelef.xyz/WebService1.asmx", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Login(string KullaniciAdi, string Parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> LoginAsync(string KullaniciAdi, string Parola);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciAdiKontrol", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool KullaniciAdiKontrol(string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciAdiKontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> KullaniciAdiKontrolAsync(string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciKayit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool KullaniciKayit(string kullaniciAdi, string sifre, string ad, string soyad, string mail, string telefon, int yas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciKayit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> KullaniciKayitAsync(string kullaniciAdi, string sifre, string ad, string soyad, string mail, string telefon, int yas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/SifremiUnuttum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SifremiUnuttum(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/SifremiUnuttum", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SifremiUnuttumAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/SahaGoster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SahaGoster(string ilAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/SahaGoster", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SahaGosterAsync(string ilAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string KullaniciGetir(string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> KullaniciGetirAsync(string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool KullaniciGuncelle(string KulAdi, string Sifre, string Adi, string Soyadi, string Mail, string Telefon, string Yas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> KullaniciGuncelleAsync(string KulAdi, string Sifre, string Adi, string Soyadi, string Mail, string Telefon, string Yas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/SahaKirala", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool SahaKirala(string KullaniciAdi, string Adi, string Telefon, string IlAdi, string SahaAdi, string MacSaati);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/SahaKirala", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> SahaKiralaAsync(string KullaniciAdi, string Adi, string Telefon, string IlAdi, string SahaAdi, string MacSaati);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciAdTelefonGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string KullaniciAdTelefonGetir(string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/KullaniciAdTelefonGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> KullaniciAdTelefonGetirAsync(string KullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/MaclariGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MaclariGetir(string kullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/MaclariGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MaclariGetirAsync(string kullaniciAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/MacSayisi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int MacSayisi(string kullaniciAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/MacSayisi", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MacSayisiAsync(string kullaniciAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/yoneticiIDgetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int yoneticiIDgetir(string ymail, string ysifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/yoneticiIDgetir", ReplyAction="*")]
        System.Threading.Tasks.Task<int> yoneticiIDgetirAsync(string ymail, string ysifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/yoneticiLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool yoneticiLogin(string yMail, string ySifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/yoneticiLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> yoneticiLoginAsync(string yMail, string ySifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/yoneticiAdSoyadGetir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string yoneticiAdSoyadGetir(string ymail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/yoneticiAdSoyadGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> yoneticiAdSoyadGetirAsync(string ymail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/sahaSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool sahaSil(int sahaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/sahaSil", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> sahaSilAsync(int sahaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/sahaListele", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable sahaListele(int yID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://repo.bahadirtelef.xyz/WebService1.asmx/sahaListele", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> sahaListeleAsync(int yID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HaliSahaUygulamasi.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HaliSahaUygulamasi.ServiceReference1.WebService1Soap>, HaliSahaUygulamasi.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public bool Login(string KullaniciAdi, string Parola) {
            return base.Channel.Login(KullaniciAdi, Parola);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string KullaniciAdi, string Parola) {
            return base.Channel.LoginAsync(KullaniciAdi, Parola);
        }
        
        public bool KullaniciAdiKontrol(string KullaniciAdi) {
            return base.Channel.KullaniciAdiKontrol(KullaniciAdi);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciAdiKontrolAsync(string KullaniciAdi) {
            return base.Channel.KullaniciAdiKontrolAsync(KullaniciAdi);
        }
        
        public bool KullaniciKayit(string kullaniciAdi, string sifre, string ad, string soyad, string mail, string telefon, int yas) {
            return base.Channel.KullaniciKayit(kullaniciAdi, sifre, ad, soyad, mail, telefon, yas);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciKayitAsync(string kullaniciAdi, string sifre, string ad, string soyad, string mail, string telefon, int yas) {
            return base.Channel.KullaniciKayitAsync(kullaniciAdi, sifre, ad, soyad, mail, telefon, yas);
        }
        
        public bool SifremiUnuttum(string Email) {
            return base.Channel.SifremiUnuttum(Email);
        }
        
        public System.Threading.Tasks.Task<bool> SifremiUnuttumAsync(string Email) {
            return base.Channel.SifremiUnuttumAsync(Email);
        }
        
        public string SahaGoster(string ilAdi) {
            return base.Channel.SahaGoster(ilAdi);
        }
        
        public System.Threading.Tasks.Task<string> SahaGosterAsync(string ilAdi) {
            return base.Channel.SahaGosterAsync(ilAdi);
        }
        
        public string KullaniciGetir(string KullaniciAdi) {
            return base.Channel.KullaniciGetir(KullaniciAdi);
        }
        
        public System.Threading.Tasks.Task<string> KullaniciGetirAsync(string KullaniciAdi) {
            return base.Channel.KullaniciGetirAsync(KullaniciAdi);
        }
        
        public bool KullaniciGuncelle(string KulAdi, string Sifre, string Adi, string Soyadi, string Mail, string Telefon, string Yas) {
            return base.Channel.KullaniciGuncelle(KulAdi, Sifre, Adi, Soyadi, Mail, Telefon, Yas);
        }
        
        public System.Threading.Tasks.Task<bool> KullaniciGuncelleAsync(string KulAdi, string Sifre, string Adi, string Soyadi, string Mail, string Telefon, string Yas) {
            return base.Channel.KullaniciGuncelleAsync(KulAdi, Sifre, Adi, Soyadi, Mail, Telefon, Yas);
        }
        
        public bool SahaKirala(string KullaniciAdi, string Adi, string Telefon, string IlAdi, string SahaAdi, string MacSaati) {
            return base.Channel.SahaKirala(KullaniciAdi, Adi, Telefon, IlAdi, SahaAdi, MacSaati);
        }
        
        public System.Threading.Tasks.Task<bool> SahaKiralaAsync(string KullaniciAdi, string Adi, string Telefon, string IlAdi, string SahaAdi, string MacSaati) {
            return base.Channel.SahaKiralaAsync(KullaniciAdi, Adi, Telefon, IlAdi, SahaAdi, MacSaati);
        }
        
        public string KullaniciAdTelefonGetir(string KullaniciAdi) {
            return base.Channel.KullaniciAdTelefonGetir(KullaniciAdi);
        }
        
        public System.Threading.Tasks.Task<string> KullaniciAdTelefonGetirAsync(string KullaniciAdi) {
            return base.Channel.KullaniciAdTelefonGetirAsync(KullaniciAdi);
        }
        
        public string MaclariGetir(string kullaniciAdi) {
            return base.Channel.MaclariGetir(kullaniciAdi);
        }
        
        public System.Threading.Tasks.Task<string> MaclariGetirAsync(string kullaniciAdi) {
            return base.Channel.MaclariGetirAsync(kullaniciAdi);
        }
        
        public int MacSayisi(string kullaniciAd) {
            return base.Channel.MacSayisi(kullaniciAd);
        }
        
        public System.Threading.Tasks.Task<int> MacSayisiAsync(string kullaniciAd) {
            return base.Channel.MacSayisiAsync(kullaniciAd);
        }
        
        public int yoneticiIDgetir(string ymail, string ysifre) {
            return base.Channel.yoneticiIDgetir(ymail, ysifre);
        }
        
        public System.Threading.Tasks.Task<int> yoneticiIDgetirAsync(string ymail, string ysifre) {
            return base.Channel.yoneticiIDgetirAsync(ymail, ysifre);
        }
        
        public bool yoneticiLogin(string yMail, string ySifre) {
            return base.Channel.yoneticiLogin(yMail, ySifre);
        }
        
        public System.Threading.Tasks.Task<bool> yoneticiLoginAsync(string yMail, string ySifre) {
            return base.Channel.yoneticiLoginAsync(yMail, ySifre);
        }
        
        public string yoneticiAdSoyadGetir(string ymail) {
            return base.Channel.yoneticiAdSoyadGetir(ymail);
        }
        
        public System.Threading.Tasks.Task<string> yoneticiAdSoyadGetirAsync(string ymail) {
            return base.Channel.yoneticiAdSoyadGetirAsync(ymail);
        }
        
        public bool sahaSil(int sahaID) {
            return base.Channel.sahaSil(sahaID);
        }
        
        public System.Threading.Tasks.Task<bool> sahaSilAsync(int sahaID) {
            return base.Channel.sahaSilAsync(sahaID);
        }
        
        public System.Data.DataTable sahaListele(int yID) {
            return base.Channel.sahaListele(yID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> sahaListeleAsync(int yID) {
            return base.Channel.sahaListeleAsync(yID);
        }
    }
}
